# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: River's Blog
subtitle: I am a freelance programmer
description: ""
author: River Yang
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.riverrun.xyz
root: ""
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: huxblog

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:



#Custom Setting Start

# Site settings
SEOTitle: River的博客 | River's Blog
header-img: img/home-bg.jpg
email: revir.qing@gmail.com
keyword: ""

# SNS settings
# RSS: false
zhihu_username:     revir
github_username:    revir
twitter_username:   revir_qing
linkedin_username:  revir

# Build settings
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Disqus settings
disqus_username: riverrun

# Duoshuo settings
# duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false                     # set to false if you want to use Comment without Sharing

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "freelance programmer, full-stack developer"
sidebar-avatar: img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
      title: "Leyafo's Blog",
      href: "http://www.leyafo.com"
    },
    {
        title: "Kaijun's Blog",
        href: "http://blog.kaijun.rocks"
    },{
        title: "Hux Blog",
        href: "http://huangxuan.me"
    }
]

#Custom Setting End
